package com.jfinal.weixin.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbTemperatureRecord<M extends BaseTbTemperatureRecord<M>> extends Model<M> implements IBean {

	public M setChannelId(java.lang.Integer channelId) {
		set("channel_id", channelId);
		return (M)this;
	}
	
	public java.lang.Integer getChannelId() {
		return getInt("channel_id");
	}

	public M setFrameId(java.lang.Integer frameId) {
		set("frame_id", frameId);
		return (M)this;
	}
	
	public java.lang.Integer getFrameId() {
		return getInt("frame_id");
	}

	public M setTrackId(java.lang.Integer trackId) {
		set("track_id", trackId);
		return (M)this;
	}
	
	public java.lang.Integer getTrackId() {
		return getInt("track_id");
	}

	public M setScanTimestamp(java.lang.Long scanTimestamp) {
		set("scan_timestamp", scanTimestamp);
		return (M)this;
	}
	
	public java.lang.Long getScanTimestamp() {
		return getLong("scan_timestamp");
	}

	public M setImagePath(java.lang.String imagePath) {
		set("image_path", imagePath);
		return (M)this;
	}
	
	public java.lang.String getImagePath() {
		return getStr("image_path");
	}

	public M setTemperature(java.lang.Double temperature) {
		set("temperature", temperature);
		return (M)this;
	}
	
	public java.lang.Double getTemperature() {
		return getDouble("temperature");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setScore(java.lang.Float score) {
		set("score", score);
		return (M)this;
	}
	
	public java.lang.Float getScore() {
		return getFloat("score");
	}

	public M setTag(java.lang.String tag) {
		set("tag", tag);
		return (M)this;
	}
	
	public java.lang.String getTag() {
		return getStr("tag");
	}

	public M setIp(java.lang.Integer ip) {
		set("ip", ip);
		return (M)this;
	}
	
	public java.lang.Integer getIp() {
		return getInt("ip");
	}

}
