package com.jfinal.weixin.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWUser<M extends BaseWUser<M>> extends Model<M> implements IBean {

	public M setid(java.lang.Integer  id) {
		set("id",  id);
		return (M)this;
	}
	
	public java.lang.Integer getid() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setIdno(java.lang.String idno) {
		set("idno", idno);
		return (M)this;
	}
	
	public java.lang.String getIdno() {
		return getStr("idno");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public M setExt1(java.lang.String ext1) {
		set("ext1", ext1);
		return (M)this;
	}
	
	public java.lang.String getExt1() {
		return getStr("ext1");
	}

	public M setExt2(java.lang.String ext2) {
		set("ext2", ext2);
		return (M)this;
	}
	
	public java.lang.String getExt2() {
		return getStr("ext2");
	}

	public M setExt3(java.lang.String ext3) {
		set("ext3", ext3);
		return (M)this;
	}
	
	public java.lang.String getExt3() {
		return getStr("ext3");
	}

}
