package com.jfinal.weixin.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbGroup<M extends BaseTbGroup<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setGroupName(java.lang.String groupName) {
		set("groupName", groupName);
		return (M)this;
	}
	
	public java.lang.String getGroupName() {
		return getStr("groupName");
	}

	public M setCreationDate(java.lang.String creationDate) {
		set("creationDate", creationDate);
		return (M)this;
	}
	
	public java.lang.String getCreationDate() {
		return getStr("creationDate");
	}

	public M setUpdateDate(java.lang.String updateDate) {
		set("updateDate", updateDate);
		return (M)this;
	}
	
	public java.lang.String getUpdateDate() {
		return getStr("updateDate");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public M setExpt2(java.lang.String expt2) {
		set("expt2", expt2);
		return (M)this;
	}
	
	public java.lang.String getExpt2() {
		return getStr("expt2");
	}

}
