package com.jfinal.weixin.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbStatement<M extends BaseTbStatement<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserName(java.lang.String userName) {
		set("userName", userName);
		return (M)this;
	}
	
	public java.lang.String getUserName() {
		return getStr("userName");
	}

	public M setStudentNumber(java.lang.String studentNumber) {
		set("studentNumber", studentNumber);
		return (M)this;
	}
	
	public java.lang.String getStudentNumber() {
		return getStr("studentNumber");
	}

	public M setGroupName(java.lang.String groupName) {
		set("groupName", groupName);
		return (M)this;
	}
	
	public java.lang.String getGroupName() {
		return getStr("groupName");
	}

	public M setAnimalHeat(java.lang.String animalHeat) {
		set("animalHeat", animalHeat);
		return (M)this;
	}
	
	public java.lang.String getAnimalHeat() {
		return getStr("animalHeat");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public M setDormitory(java.lang.String dormitory) {
		set("dormitory", dormitory);
		return (M)this;
	}
	
	public java.lang.String getDormitory() {
		return getStr("dormitory");
	}

	public M setIsAccommodation(java.lang.String isAccommodation) {
		set("isAccommodation", isAccommodation);
		return (M)this;
	}
	
	public java.lang.String getIsAccommodation() {
		return getStr("isAccommodation");
	}

	public M setDate(java.lang.String date) {
		set("date", date);
		return (M)this;
	}
	
	public java.lang.String getDate() {
		return getStr("date");
	}

	public M setExpt2(java.lang.String expt2) {
		set("expt2", expt2);
		return (M)this;
	}
	
	public java.lang.String getExpt2() {
		return getStr("expt2");
	}

	public M setSchoolId(java.lang.Integer schoolId) {
		set("schoolId", schoolId);
		return (M)this;
	}
	
	public java.lang.Integer getSchoolId() {
		return getInt("schoolId");
	}

}
