package com.jfinal.weixin.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTblDevice<M extends BaseTblDevice<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSchoolId(java.lang.Integer schoolId) {
		set("schoolId", schoolId);
		return (M)this;
	}
	
	public java.lang.Integer getSchoolId() {
		return getInt("schoolId");
	}

	public M setSwjCode(java.lang.String swjCode) {
		set("swjCode", swjCode);
		return (M)this;
	}
	
	public java.lang.String getSwjCode() {
		return getStr("swjCode");
	}

}
