package com.jfinal.weixin.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbPersonnel<M extends BaseTbPersonnel<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setGroupName(java.lang.String groupName) {
		set("groupName", groupName);
		return (M)this;
	}
	
	public java.lang.String getGroupName() {
		return getStr("groupName");
	}

	public M setUserName(java.lang.String userName) {
		set("userName", userName);
		return (M)this;
	}
	
	public java.lang.String getUserName() {
		return getStr("userName");
	}

	public M setStudentNumber(java.lang.Integer studentNumber) {
		set("studentNumber", studentNumber);
		return (M)this;
	}
	
	public java.lang.Integer getStudentNumber() {
		return getInt("studentNumber");
	}

	public M setDormitory(java.lang.String dormitory) {
		set("dormitory", dormitory);
		return (M)this;
	}
	
	public java.lang.String getDormitory() {
		return getStr("dormitory");
	}

	public M setIsAccommodation(java.lang.String isAccommodation) {
		set("isAccommodation", isAccommodation);
		return (M)this;
	}
	
	public java.lang.String getIsAccommodation() {
		return getStr("isAccommodation");
	}

	public M setCreationDate(java.lang.String creationDate) {
		set("creationDate", creationDate);
		return (M)this;
	}
	
	public java.lang.String getCreationDate() {
		return getStr("creationDate");
	}

	public M setUpdateDate(java.lang.String updateDate) {
		set("updateDate", updateDate);
		return (M)this;
	}
	
	public java.lang.String getUpdateDate() {
		return getStr("updateDate");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public M setExpt1(java.lang.String expt1) {
		set("expt1", expt1);
		return (M)this;
	}
	
	public java.lang.String getExpt1() {
		return getStr("expt1");
	}

}
