package com.jfinal.weixin.model;

import com.jfinal.weixin.model.base.BaseTbAccessrecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbAccessrecord extends BaseTbAccessrecord<TbAccessrecord> {
	public static final TbAccessrecord dao = new TbAccessrecord().dao();
}
