package com.jfinal.weixin.model;

import com.jfinal.weixin.model.base.BaseTbBuilding;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbBuilding extends BaseTbBuilding<TbBuilding> {
	public static final TbBuilding dao = new TbBuilding().dao();
}
