package com.jfinal.weixin.model;

import com.jfinal.weixin.model.base.BaseTbDevicerelated;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbDevicerelated extends BaseTbDevicerelated<TbDevicerelated> {
	public static final TbDevicerelated dao = new TbDevicerelated().dao();
}
