package com.jfinal.weixin.model;

import com.jfinal.weixin.model.base.BaseTbGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbGroup extends BaseTbGroup<TbGroup> {
	public static final TbGroup dao = new TbGroup().dao();
}
