package com.jfinal.weixin.model;

import com.jfinal.weixin.model.base.BaseTblDevice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblDevice extends BaseTblDevice<TblDevice> {
	public static final TblDevice dao = new TblDevice().dao();
}
