package com.jfinal.weixin.model;

import com.jfinal.weixin.model.base.BaseTblPosp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblPosp extends BaseTblPosp<TblPosp> {
	public static final TblPosp dao = new TblPosp().dao();
}
