package com.jfinal.weixin.model;

import com.jfinal.weixin.model.base.BaseTblSchool;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblSchool extends BaseTblSchool<TblSchool> {
	public static final TblSchool dao = new TblSchool().dao();
}
