package com.jfinal.weixin.model;

import com.jfinal.weixin.model.base.BaseTbPersonnel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbPersonnel extends BaseTbPersonnel<TbPersonnel> {
	public static final TbPersonnel dao = new TbPersonnel().dao();
}
