package com.jfinal.weixin.model;

import com.jfinal.weixin.model.base.BaseTbPtinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbPtinfo extends BaseTbPtinfo<TbPtinfo> {
	public static final TbPtinfo dao = new TbPtinfo().dao();
}
