package com.jfinal.weixin.model;

import com.jfinal.weixin.model.base.BaseTbServerinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbServerinfo extends BaseTbServerinfo<TbServerinfo> {
	public static final TbServerinfo dao = new TbServerinfo().dao();
}
