package com.jfinal.weixin.model;

import com.jfinal.weixin.model.base.BaseTbStatement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbStatement extends BaseTbStatement<TbStatement> {
	public static final TbStatement dao = new TbStatement().dao();
}
