package com.jfinal.weixin.model;

import com.jfinal.weixin.model.base.BaseTbTemperatureRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbTemperatureRecord extends BaseTbTemperatureRecord<TbTemperatureRecord> {
	public static final TbTemperatureRecord dao = new TbTemperatureRecord().dao();
}
