package com.jfinal.weixin.model;

import com.jfinal.weixin.model.base.BaseTxBanner;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TxBanner extends BaseTxBanner<TxBanner> {
	public static final TxBanner dao = new TxBanner().dao();
}
