package com.jfinal.weixin.model;

import com.jfinal.weixin.model.base.BaseTxNews;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TxNews extends BaseTxNews<TxNews> {
	public static final TxNews dao = new TxNews().dao();
}
