package com.jfinal.weixin.model;

import com.jfinal.weixin.model.base.BaseTxNotice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TxNotice extends BaseTxNotice<TxNotice> {
	public static final TxNotice dao = new TxNotice().dao();
}
