package com.jfinal.weixin.model;

import com.jfinal.weixin.model.base.BaseTxOption;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TxOption extends BaseTxOption<TxOption> {
	public static final TxOption dao = new TxOption().dao();
}
