package com.jfinal.weixin.model;

import com.jfinal.weixin.model.base.BaseTxUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TxUser extends BaseTxUser<TxUser> {
	public static final TxUser dao = new TxUser().dao();
}
