package com.jfinal.weixin.model;

import com.jfinal.weixin.model.base.BaseWUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WUser extends BaseWUser<WUser> {
	public static final WUser dao = new WUser().dao();
}
